import Head from "next/head";
import Image from "next/image";
import About from "../components/About";
import Main from "../components/Main";
import NavBar from "../components/NavBar";
import Skills from "../components/Skills";
import Projects from "../components/Projects";
import Contact from "../components/Contact";

export default function Home() {
	return (
		<div>
			<Head>
				<title>Chris De Leon | Software Engineer | Volleyballer</title>
				<meta name="description" content="Generated by create next app" />
				<link
					rel="icon"
					href="/wife.jpg
				"
				/>
			</Head>
			<NavBar />
			<Main />
			<About />
			<Skills />
			<Projects />
			<Contact />
		</div>
	);
}
